# Generated by Django 4.1 on 2023-08-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_code', models.IntegerField()),
                ('e_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('attendance', models.CharField(max_length=1)),
            ],
        ),
    ]
